language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - LARAVEL=5.7.* PHPUNIT=^7.0
    - LARAVEL=5.7.* PHPUNIT=^8.0
    - LARAVEL=5.8.* PHPUNIT=^7.0
    - LARAVEL=5.8.* PHPUNIT=^8.0
    - LARAVEL=dev-master PHPUNIT=^7.0
    - LARAVEL=dev-master PHPUNIT=^8.0

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: LARAVEL=5.7.* PHPUNIT=^8.0
    - php: 7.1
      env: LARAVEL=5.8.* PHPUNIT=^8.0
    - php: 7.1
      env: LARAVEL=dev-master PHPUNIT=^7.0
    - php: 7.1
      env: LARAVEL=dev-master PHPUNIT=^8.0
  allow_failures:
    - env: LARAVEL=dev-master PHPUNIT=^7.0
    - env: LARAVEL=dev-master PHPUNIT=^8.0

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - travis_retry composer require "laravel/framework=${LARAVEL}" "phpunit/phpunit:${PHPUNIT}" --dev --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit --verbose
